# .github/workflows/docker-publish.yml

name: Construir y Desplegar en Google Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}
  GAR_REPOSITORY: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPOSITORY }}
  SERVICE_NAME: bread-api-service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # <-- Permiso clave para Workload Identity Federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ðŸž Depurar Valores de Secrets
        run: |
          echo "Project ID usado: [${{ secrets.GCP_PROJECT_ID }}]"
          echo "GAR Location usado: [${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}]"
          echo "GAR Repository usado: [${{ secrets.GCP_ARTIFACT_REGISTRY_REPOSITORY }}]"

      - name: Autenticar en Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configurar Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Construir imagen Docker
        run: |-
          docker build \
            --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" \
            .

      - name: Publicar imagen en Artifact Registry
        run: |-
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      - name: Desplegar en Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.GAR_LOCATION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          flags: '--allow-unauthenticated'
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}